# ======================
# APACHE SPARK SERVICE
# ======================
services:
  spark-master:
    build:
      context: .
      dockerfile: Dockerfile
    image: apache_spark:01
    container_name: spark-master
    restart: unless-stopped
    command: >
      /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master
    ports:
      - ${PROD_PORT_LOCAL_WORKER}:${PROD_PORT_WORKER}
      - ${PROD_PORT_LOCAL_MASTER}:${PROD_PORT_MASTER}
    networks:
      - tesis-net
    user: ${PROD_USER_SPARK}:${PROD_GROUP_SPARK}
    volumes:
      - ./projects:/opt/spark/projects
      #- ../extra_jars:/opt/spark/extra_jars
      - ./logs:/opt/spark/logs
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 30s
      timeout: 10s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 2G
          

  spark-worker:
    build:
      context: .
      dockerfile: Dockerfile
    image: apache_spark:01
    container_name: spark-worker
    restart: unless-stopped
    command: >
      /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    depends_on:
      - spark-master
    networks:
      - tesis-net
    user: ${PROD_USER_SPARK}:${PROD_USER_SPARK}
    volumes:
      - ./projects:/opt/spark/projects
      #- ../extra_jars:/opt/spark/extra_jars
      - ./logs:/opt/spark/logs
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "bash", "-c", "pgrep -f 'org.apache.spark.deploy.worker.Worker' >/dev/null"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 20s
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 2G

networks:
  tesis-net:
    name: tesis-net
    external: true
