spark.master spark://spark-master:7077

spark.driver.memory 2g
spark.executor.memory 2g
spark.executor.cores 2
spark.executor.instances 2

spark.sql.shuffle.partitions 200

spark.dynamicAllocation.enabled true
spark.dynamicAllocation.minExecutors 2
spark.dynamicAllocation.maxExecutors 10

spark.eventLog.enabled true
spark.eventLog.dir /opt/spark/logs/events
spark.history.fs.logDirectory /opt/spark/logs/history

spark.authenticate true
spark.network.crypto.enabled true
spark.ssl.enabled false
spark.authenticate.secret SuperSecretKey123

spark.serializer org.apache.spark.serializer.KryoSerializer
spark.sql.autoBroadcastJoinThreshold 10MB
spark.sql.adaptive.enabled true


spark.hadoop.fs.permissions.umask-mode 022
